from __future__ import annotations
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from typing import Any

from .stats import Stats

from functools import partial


class Champion:

    def __init__(self, name, level=1, ad=0, ap=0,base_aspd=0, as_ratio=0, cs=0, csd=175, ar=0, mr=0, hp=0, mana = 0,
                 ad_growth=0, ap_growth=0, aspd_growth=0, ar_growth=0, mr_growth=0, hp_growth=0, mana_growth=0) -> None:

        self.base_stats = Stats(ad=ad, ap=ap,cs=cs, csd=csd, 
                                ar=ar, mr=mr, hp=hp, mana=mana)



        self.ad_growth = ad_growth
        self.ap_growth = ap_growth
        self.aspd_growth = aspd_growth
        self.ar_growth = ar_growth
        self.mr_growth = mr_growth
        self.hp_growth = hp_growth
        self.mana_growth = mana_growth
        self.base_aspd = base_aspd
        self.as_ratio = base_aspd if as_ratio == 0 else as_ratio #if the as_ratio is not set then its base_aspd

        self.name = name
        self.level = level
        self.generate_bonus_stats(level)


    def generate_bonus_stats(self, level):
        # simplify function call.
        f = partial(growth_formula, level)
        self.bonus_stats = Stats(ad=f(self.ad_growth), ap=f(self.ap_growth), aspd=f(self.aspd_growth),
                                 ar=f(self.ar_growth), mr=f(self.mr_growth), hp=f(self.hp_growth), mana=f(self.mana_growth))

        self.current_stats = self.base_stats + self.bonus_stats

    def level_up(self):
        if self.level < 18:
            self.level += 1
            self.generate_bonus_stats(self.level)


    # forward the attributes from curent_stats so inventory can be used as a stats object
    #TODO: this feels hacky
    def __getattribute__(self, name: str) -> Any:
        try:
            return super().__getattribute__(name)
        except:
            return self.current_stats.__dict__[name]


def growth_formula(level, growth):
    return growth * (level-1) * (0.7025 + 0.0175 * (level-1))


from functools import partial

TargetDummy = partial(Champion, name="Target Dummy", hp=1000)

### CHAMPIONS ###

# Autogenerated champion code

Aatrox = partial(Champion, name="Aatrox", ad=60, ad_growth=5, hp=650, hp_growth=104, ar=38, ar_growth=4.45, mr=32,
            mr_growth=2.05, base_aspd=0.651, aspd_growth=2.5, as_ratio=0, mana=0, mana_growth=0)
Ahri = partial(Champion, name="Ahri", ad=53, ad_growth=3, hp=570, hp_growth=96, ar=18, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.668, aspd_growth=2, as_ratio=0, mana=418, mana_growth=25)
Akali = partial(Champion, name="Akali", ad=62, ad_growth=3.3, hp=570, hp_growth=119, ar=23, ar_growth=4.7, mr=37,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=3.2, as_ratio=0, mana=200, mana_growth=0)
Akshan = partial(Champion, name="Akshan", ad=52, ad_growth=3.5, hp=630, hp_growth=104, ar=26, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.638, aspd_growth=4, as_ratio=0.4, mana=350, mana_growth=40)
Alistar = partial(Champion, name="Alistar", ad=62, ad_growth=3.75, hp=670, hp_growth=120, ar=44, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=2.125, as_ratio=0, mana=350, mana_growth=40)
Amumu = partial(Champion, name="Amumu", ad=53, ad_growth=3.8, hp=685, hp_growth=89, ar=30, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.736, aspd_growth=2.18, as_ratio=0.638, mana=285, mana_growth=40)
Anivia = partial(Champion, name="Anivia", ad=51, ad_growth=3.2, hp=550, hp_growth=96, ar=21, ar_growth=5.2, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.68, as_ratio=0, mana=495, mana_growth=45)
Annie = partial(Champion, name="Annie", ad=50, ad_growth=2.63, hp=594, hp_growth=102, ar=19, ar_growth=5.2, mr=30,
            mr_growth=1.3, base_aspd=0.579, aspd_growth=1.36, as_ratio=0, mana=418, mana_growth=25)
Aphelios = partial(Champion, name="Aphelios", ad=55, ad_growth=3, hp=580, hp_growth=102, ar=26, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.64, aspd_growth=2.1, as_ratio=0, mana=348, mana_growth=42)
Ashe = partial(Champion, name="Ashe", ad=59, ad_growth=2.96, hp=640, hp_growth=101, ar=26, ar_growth=4.6, mr=30,
            mr_growth=1.3, base_aspd=0.658, aspd_growth=3.33, as_ratio=0, mana=280, mana_growth=32)
AurelionSol = partial(Champion, name="AurelionSol", ad=57, ad_growth=3.2, hp=645, hp_growth=106, ar=19, ar_growth=4.8, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.36, as_ratio=0, mana=350, mana_growth=50)
Azir = partial(Champion, name="Azir", ad=52, ad_growth=2.8, hp=622, hp_growth=119, ar=19, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=3, as_ratio=0, mana=480, mana_growth=21)
Bard = partial(Champion, name="Bard", ad=52, ad_growth=3, hp=630, hp_growth=103, ar=34, ar_growth=5.2, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2, as_ratio=0, mana=350, mana_growth=50)
Blitzcrank = partial(Champion, name="Blitzcrank", ad=62, ad_growth=3.5, hp=653, hp_growth=109, ar=40, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=1.13, as_ratio=0, mana=267, mana_growth=40)
Brand = partial(Champion, name="Brand", ad=57, ad_growth=3, hp=590, hp_growth=102, ar=22, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.36, as_ratio=0, mana=469, mana_growth=21)
Braum = partial(Champion, name="Braum", ad=55, ad_growth=3.2, hp=610, hp_growth=112, ar=47, ar_growth=5.2, mr=32,
            mr_growth=2.05, base_aspd=0.644, aspd_growth=3.5, as_ratio=0, mana=311, mana_growth=45)
Caitlyn = partial(Champion, name="Caitlyn", ad=62, ad_growth=3.4, hp=580, hp_growth=107, ar=28, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.681, aspd_growth=4, as_ratio=0.568, mana=315, mana_growth=35)
Camille = partial(Champion, name="Camille", ad=68, ad_growth=3.5, hp=646, hp_growth=99, ar=35, ar_growth=5, mr=32.1,
            mr_growth=2.05, base_aspd=0.644, aspd_growth=2.5, as_ratio=0, mana=339, mana_growth=52)
Cassiopeia = partial(Champion, name="Cassiopeia", ad=53, ad_growth=3, hp=630, hp_growth=104, ar=18, ar_growth=4.7, mr=32,
            mr_growth=1.3, base_aspd=0.647, aspd_growth=1.5, as_ratio=0, mana=350, mana_growth=60)
Chogath = partial(Champion, name="Chogath", ad=69, ad_growth=4.2, hp=644, hp_growth=94, ar=38, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=1.44, as_ratio=0, mana=270, mana_growth=60)
Corki = partial(Champion, name="Corki", ad=55, ad_growth=2.5, hp=588, hp_growth=101, ar=28, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.638, aspd_growth=2.3, as_ratio=0, mana=350, mana_growth=54)
Darius = partial(Champion, name="Darius", ad=64, ad_growth=5, hp=652, hp_growth=114, ar=39, ar_growth=5.2, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=1, as_ratio=0, mana=263, mana_growth=57.5)
Diana = partial(Champion, name="Diana", ad=57, ad_growth=3, hp=640, hp_growth=109, ar=31, ar_growth=4.3, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=2.25, as_ratio=0, mana=375, mana_growth=25)
Draven = partial(Champion, name="Draven", ad=62, ad_growth=3.61, hp=675, hp_growth=104, ar=29, ar_growth=4.5, mr=30,
            mr_growth=1.3, base_aspd=0.679, aspd_growth=2.7, as_ratio=0, mana=360.56, mana_growth=39)
DrMundo = partial(Champion, name="DrMundo", ad=61, ad_growth=3.5, hp=653, hp_growth=103, ar=32, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.72, aspd_growth=3.3, as_ratio=0.625, mana=0, mana_growth=0)
Ekko = partial(Champion, name="Ekko", ad=58, ad_growth=3, hp=655, hp_growth=99, ar=32, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.688, aspd_growth=3.3, as_ratio=0.625, mana=280, mana_growth=70)
Elise = partial(Champion, name="Elise", ad=55, ad_growth=3, hp=625, hp_growth=107, ar=27, ar_growth=5.2, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.75, as_ratio=0, mana=324, mana_growth=50)
Evelynn = partial(Champion, name="Evelynn", ad=61, ad_growth=3, hp=642, hp_growth=98, ar=37, ar_growth=4.7, mr=32.1,
            mr_growth=2.05, base_aspd=0.667, aspd_growth=2.1, as_ratio=0, mana=315, mana_growth=42)
Ezreal = partial(Champion, name="Ezreal", ad=60, ad_growth=2.5, hp=600, hp_growth=102, ar=24, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.5, as_ratio=0, mana=375, mana_growth=70)
Fiddlesticks = partial(Champion, name="Fiddlesticks", ad=55.36, ad_growth=2.63, hp=650.4, hp_growth=106, ar=34, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.11, as_ratio=0, mana=500, mana_growth=28)
Fiora = partial(Champion, name="Fiora", ad=68, ad_growth=3.3, hp=620, hp_growth=99, ar=33, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.69, aspd_growth=3.2, as_ratio=0, mana=300, mana_growth=60)
Fizz = partial(Champion, name="Fizz", ad=58, ad_growth=3, hp=640, hp_growth=112, ar=22, ar_growth=4.6, mr=32,
            mr_growth=2.05, base_aspd=0.658, aspd_growth=3.1, as_ratio=0, mana=317, mana_growth=37)
Galio = partial(Champion, name="Galio", ad=59, ad_growth=3.5, hp=632, hp_growth=126, ar=24, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=1.5, as_ratio=0, mana=500, mana_growth=40)
Gangplank = partial(Champion, name="Gangplank", ad=64, ad_growth=4, hp=640, hp_growth=104, ar=35, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.658, aspd_growth=3.2, as_ratio=0.69, mana=280, mana_growth=60)
Garen = partial(Champion, name="Garen", ad=66, ad_growth=4.5, hp=690, hp_growth=98, ar=36, ar_growth=4.2, mr=32,
            mr_growth=1.55, base_aspd=0.625, aspd_growth=3.65, as_ratio=0, mana=0, mana_growth=0)
Gnar = partial(Champion, name="Gnar", ad=57, ad_growth=3, hp=580, hp_growth=79, ar=32, ar_growth=3.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=6, as_ratio=0, mana=100, mana_growth=0)
Gragas = partial(Champion, name="Gragas", ad=64, ad_growth=3.5, hp=670, hp_growth=109, ar=38, ar_growth=4.8, mr=32,
            mr_growth=2.05, base_aspd=0.675, aspd_growth=2.05, as_ratio=0.625, mana=400, mana_growth=47)
Graves = partial(Champion, name="Graves", ad=68, ad_growth=4, hp=625, hp_growth=106, ar=33, ar_growth=4.6, mr=32,
            mr_growth=2.05, base_aspd=0.475, aspd_growth=2.6, as_ratio=0.49, mana=325, mana_growth=40)
Gwen = partial(Champion, name="Gwen", ad=63, ad_growth=3, hp=660, hp_growth=109, ar=39, ar_growth=5.2, mr=32,
            mr_growth=2.05, base_aspd=0.69, aspd_growth=2.25, as_ratio=0, mana=330, mana_growth=40)
Hecarim = partial(Champion, name="Hecarim", ad=66, ad_growth=3.2, hp=650, hp_growth=104, ar=35, ar_growth=5.45, mr=32,
            mr_growth=2.05, base_aspd=0.67, aspd_growth=2.5, as_ratio=0, mana=277, mana_growth=60)
Heimerdinger = partial(Champion, name="Heimerdinger", ad=56, ad_growth=2.7, hp=558, hp_growth=101, ar=19, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.36, as_ratio=0, mana=385, mana_growth=20)
Illaoi = partial(Champion, name="Illaoi", ad=68, ad_growth=5, hp=656, hp_growth=109, ar=35, ar_growth=5, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=2.5, as_ratio=0, mana=300, mana_growth=50)
Irelia = partial(Champion, name="Irelia", ad=65, ad_growth=4, hp=590, hp_growth=124, ar=36, ar_growth=4.2, mr=28,
            mr_growth=2.05, base_aspd=0.656, aspd_growth=2.5, as_ratio=0, mana=350, mana_growth=50)
Ivern = partial(Champion, name="Ivern", ad=50, ad_growth=3, hp=655, hp_growth=99, ar=27, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.644, aspd_growth=3.4, as_ratio=0, mana=450, mana_growth=60)
Janna = partial(Champion, name="Janna", ad=52, ad_growth=3, hp=570, hp_growth=84, ar=28, ar_growth=5, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=3, as_ratio=0, mana=350, mana_growth=64)
JarvanIV = partial(Champion, name="JarvanIV", ad=64, ad_growth=3.4, hp=640, hp_growth=104, ar=34, ar_growth=4.8, mr=32,
            mr_growth=2.05, base_aspd=0.658, aspd_growth=2.5, as_ratio=0, mana=300, mana_growth=40)
Jax = partial(Champion, name="Jax", ad=68, ad_growth=4.25, hp=685, hp_growth=99, ar=36, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.638, aspd_growth=3.4, as_ratio=0, mana=339, mana_growth=52)
Jayce = partial(Champion, name="Jayce", ad=54, ad_growth=4.25, hp=590, hp_growth=109, ar=22, ar_growth=5, mr=30,
            mr_growth=1.3, base_aspd=0.658, aspd_growth=3, as_ratio=0, mana=375, mana_growth=45)
Jhin = partial(Champion, name="Jhin", ad=59, ad_growth=4.7, hp=655, hp_growth=107, ar=24, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=0, as_ratio=0, mana=300, mana_growth=50)
Jinx = partial(Champion, name="Jinx", ad=57, ad_growth=3.4, hp=630, hp_growth=100, ar=26, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1, as_ratio=0, mana=245, mana_growth=45)
Kaisa = partial(Champion, name="Kaisa", ad=59, ad_growth=2, hp=670, hp_growth=102, ar=28, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.644, aspd_growth=1.8, as_ratio=0, mana=344.88, mana_growth=38)
Kalista = partial(Champion, name="Kalista", ad=69, ad_growth=3.5, hp=604, hp_growth=114, ar=24, ar_growth=5.2, mr=30,
            mr_growth=1.3, base_aspd=0.694, aspd_growth=4.5, as_ratio=0, mana=300, mana_growth=45)
Karma = partial(Champion, name="Karma", ad=51, ad_growth=3.3, hp=604, hp_growth=109, ar=28, ar_growth=5, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.3, as_ratio=0, mana=374, mana_growth=50)
Karthus = partial(Champion, name="Karthus", ad=46, ad_growth=3.25, hp=620, hp_growth=101, ar=18, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.11, as_ratio=0, mana=467, mana_growth=30.5)
Kassadin = partial(Champion, name="Kassadin", ad=59, ad_growth=3.9, hp=646, hp_growth=119, ar=19, ar_growth=4, mr=30,
            mr_growth=1.3, base_aspd=0.64, aspd_growth=3.7, as_ratio=0, mana=400, mana_growth=87)
Katarina = partial(Champion, name="Katarina", ad=58, ad_growth=3.2, hp=672, hp_growth=108, ar=28, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.658, aspd_growth=2.74, as_ratio=0, mana=0, mana_growth=0)
Kayle = partial(Champion, name="Kayle", ad=50, ad_growth=2.5, hp=670, hp_growth=99, ar=26, ar_growth=4.2, mr=26,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.5, as_ratio=0.667, mana=330, mana_growth=50)
Kayn = partial(Champion, name="Kayn", ad=68, ad_growth=3.3, hp=655, hp_growth=99, ar=38, ar_growth=4.5, mr=32,
            mr_growth=2.05, base_aspd=0.669, aspd_growth=2.7, as_ratio=0, mana=410, mana_growth=50)
Kennen = partial(Champion, name="Kennen", ad=48, ad_growth=3.75, hp=611, hp_growth=98, ar=29, ar_growth=4.95, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=3.4, as_ratio=0.69, mana=200, mana_growth=0)
Khazix = partial(Champion, name="Khazix", ad=63, ad_growth=3.1, hp=643, hp_growth=99, ar=36, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.668, aspd_growth=2.7, as_ratio=0, mana=327, mana_growth=40)
Kindred = partial(Champion, name="Kindred", ad=65, ad_growth=2.5, hp=610, hp_growth=99, ar=29, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=3.5, as_ratio=0, mana=300, mana_growth=35)
Kled = partial(Champion, name="Kled", ad=65, ad_growth=3.5, hp=410, hp_growth=84, ar=35, ar_growth=5.2, mr=28,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=3.5, as_ratio=0, mana=100, mana_growth=0)
KogMaw = partial(Champion, name="KogMaw", ad=61, ad_growth=3.11, hp=635, hp_growth=99, ar=24, ar_growth=4.45, mr=30,
            mr_growth=1.3, base_aspd=0.665, aspd_growth=2.65, as_ratio=0, mana=325, mana_growth=40)
Leblanc = partial(Champion, name="Leblanc", ad=55, ad_growth=3.5, hp=598, hp_growth=111, ar=22, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.4, as_ratio=0, mana=334, mana_growth=50)
LeeSin = partial(Champion, name="LeeSin", ad=66, ad_growth=3.7, hp=645, hp_growth=99, ar=36, ar_growth=4.9, mr=32,
            mr_growth=2.05, base_aspd=0.651, aspd_growth=3, as_ratio=0, mana=200, mana_growth=0)
Leona = partial(Champion, name="Leona", ad=60, ad_growth=3, hp=646, hp_growth=101, ar=47, ar_growth=4.8, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=2.9, as_ratio=0, mana=302, mana_growth=40)
Lillia = partial(Champion, name="Lillia", ad=61, ad_growth=3.1, hp=650, hp_growth=104, ar=22, ar_growth=5.2, mr=32,
            mr_growth=1.55, base_aspd=0.625, aspd_growth=2.7, as_ratio=0, mana=410, mana_growth=50)
Lissandra = partial(Champion, name="Lissandra", ad=55, ad_growth=2.7, hp=620, hp_growth=104, ar=22, ar_growth=4.9, mr=30,
            mr_growth=1.3, base_aspd=0.656, aspd_growth=1.36, as_ratio=0.625, mana=475, mana_growth=30)
Lucian = partial(Champion, name="Lucian", ad=62, ad_growth=2.9, hp=641, hp_growth=100, ar=28, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.638, aspd_growth=3.3, as_ratio=0, mana=348.88, mana_growth=38)
Lulu = partial(Champion, name="Lulu", ad=47, ad_growth=2.6, hp=595, hp_growth=88, ar=29, ar_growth=4.9, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.25, as_ratio=0, mana=350, mana_growth=55)
Lux = partial(Champion, name="Lux", ad=54, ad_growth=3.3, hp=560, hp_growth=99, ar=19, ar_growth=5.2, mr=30,
            mr_growth=1.3, base_aspd=0.669, aspd_growth=2, as_ratio=0.625, mana=480, mana_growth=23.5)
Malphite = partial(Champion, name="Malphite", ad=62, ad_growth=4, hp=644, hp_growth=104, ar=37, ar_growth=4.95, mr=28,
            mr_growth=2.05, base_aspd=0.736, aspd_growth=3.4, as_ratio=0.638, mana=280, mana_growth=60)
Malzahar = partial(Champion, name="Malzahar", ad=55, ad_growth=3, hp=580, hp_growth=101, ar=18, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.5, as_ratio=0, mana=375, mana_growth=27.5)
Maokai = partial(Champion, name="Maokai", ad=64, ad_growth=3.3, hp=635, hp_growth=109, ar=39, ar_growth=5.2, mr=32,
            mr_growth=2.05, base_aspd=0.8, aspd_growth=2.125, as_ratio=0.695, mana=375, mana_growth=43)
MasterYi = partial(Champion, name="MasterYi", ad=66, ad_growth=3, hp=669, hp_growth=106, ar=33, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.679, aspd_growth=2, as_ratio=0, mana=251, mana_growth=42)
MissFortune = partial(Champion, name="MissFortune", ad=52, ad_growth=2.7, hp=640, hp_growth=107, ar=28, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.656, aspd_growth=3, as_ratio=0, mana=300, mana_growth=35)
MonkeyKing = partial(Champion, name="MonkeyKing", ad=68, ad_growth=3.5, hp=610, hp_growth=99, ar=31, ar_growth=4.7, mr=28,
            mr_growth=2.05, base_aspd=0.711, aspd_growth=3, as_ratio=0.658, mana=300, mana_growth=65)
Mordekaiser = partial(Champion, name="Mordekaiser", ad=61, ad_growth=4, hp=645, hp_growth=104, ar=37, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=1, as_ratio=0, mana=100, mana_growth=0)
Morgana = partial(Champion, name="Morgana", ad=56, ad_growth=3.5, hp=630, hp_growth=104, ar=25, ar_growth=5, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.53, as_ratio=0, mana=340, mana_growth=60)
Nami = partial(Champion, name="Nami", ad=51, ad_growth=3.1, hp=560, hp_growth=88, ar=29, ar_growth=5.2, mr=30,
            mr_growth=1.3, base_aspd=0.644, aspd_growth=2.61, as_ratio=0, mana=365, mana_growth=43)
Nasus = partial(Champion, name="Nasus", ad=67, ad_growth=3.5, hp=631, hp_growth=104, ar=34, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.638, aspd_growth=3.48, as_ratio=0, mana=326, mana_growth=62)
Nautilus = partial(Champion, name="Nautilus", ad=61, ad_growth=3.3, hp=646, hp_growth=100, ar=39, ar_growth=4.95, mr=32,
            mr_growth=2.05, base_aspd=0.706, aspd_growth=1, as_ratio=0.612, mana=400, mana_growth=47)
Neeko = partial(Champion, name="Neeko", ad=48, ad_growth=2.5, hp=610, hp_growth=104, ar=21, ar_growth=5.2, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=3.5, as_ratio=0.67, mana=450, mana_growth=30)
Nidalee = partial(Champion, name="Nidalee", ad=58, ad_growth=3.5, hp=610, hp_growth=109, ar=28, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.638, aspd_growth=3.22, as_ratio=0, mana=295, mana_growth=45)
Nocturne = partial(Champion, name="Nocturne", ad=62, ad_growth=3.1, hp=655, hp_growth=109, ar=38, ar_growth=4.7, mr=32,
            mr_growth=1.55, base_aspd=0.721, aspd_growth=2.7, as_ratio=0.668, mana=275, mana_growth=35)
Nunu = partial(Champion, name="Nunu", ad=61, ad_growth=3, hp=610, hp_growth=90, ar=29, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=2.25, as_ratio=0, mana=280, mana_growth=42)
Olaf = partial(Champion, name="Olaf", ad=68, ad_growth=4.7, hp=645, hp_growth=119, ar=35, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.694, aspd_growth=2.7, as_ratio=0, mana=316, mana_growth=50)
Orianna = partial(Champion, name="Orianna", ad=40, ad_growth=2.6, hp=600, hp_growth=105, ar=17, ar_growth=4.2, mr=26,
            mr_growth=1.3, base_aspd=0.658, aspd_growth=3.5, as_ratio=0, mana=418, mana_growth=25)
Ornn = partial(Champion, name="Ornn", ad=69, ad_growth=3.5, hp=660, hp_growth=109, ar=33, ar_growth=5.2, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=2, as_ratio=0, mana=340.6, mana_growth=65)
Pantheon = partial(Champion, name="Pantheon", ad=64, ad_growth=3.3, hp=650, hp_growth=109, ar=40, ar_growth=4.95, mr=28,
            mr_growth=2.05, base_aspd=0.644, aspd_growth=2.95, as_ratio=0, mana=317.12, mana_growth=31)
Poppy = partial(Champion, name="Poppy", ad=64, ad_growth=4, hp=610, hp_growth=104, ar=38, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=2.5, as_ratio=0, mana=280, mana_growth=40)
Pyke = partial(Champion, name="Pyke", ad=62, ad_growth=2, hp=670, hp_growth=104, ar=45, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.667, aspd_growth=2.5, as_ratio=0, mana=415, mana_growth=50)
Qiyana = partial(Champion, name="Qiyana", ad=66, ad_growth=3.1, hp=590, hp_growth=124, ar=28, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.688, aspd_growth=2.1, as_ratio=0.625, mana=320, mana_growth=50)
Quinn = partial(Champion, name="Quinn", ad=59, ad_growth=2.4, hp=603, hp_growth=99, ar=28, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.668, aspd_growth=3.1, as_ratio=0, mana=269, mana_growth=35)
Rakan = partial(Champion, name="Rakan", ad=62, ad_growth=3.5, hp=610, hp_growth=99, ar=32, ar_growth=5.1, mr=32,
            mr_growth=2.05, base_aspd=0.635, aspd_growth=3, as_ratio=0, mana=315, mana_growth=50)
Rammus = partial(Champion, name="Rammus", ad=56, ad_growth=3.5, hp=634, hp_growth=94, ar=36, ar_growth=5.5, mr=32,
            mr_growth=2.05, base_aspd=0.656, aspd_growth=2.215, as_ratio=0.625, mana=310, mana_growth=33)
RekSai = partial(Champion, name="RekSai", ad=64, ad_growth=3, hp=640, hp_growth=99, ar=36, ar_growth=4.95, mr=32,
            mr_growth=2.05, base_aspd=0.667, aspd_growth=2, as_ratio=0, mana=100, mana_growth=0)
Rell = partial(Champion, name="Rell", ad=55, ad_growth=3, hp=610, hp_growth=104, ar=32, ar_growth=4.2, mr=32.1,
            mr_growth=2.05, base_aspd=0.55, aspd_growth=2, as_ratio=0, mana=350, mana_growth=45)
Renata = partial(Champion, name="Renata", ad=51, ad_growth=3, hp=595, hp_growth=94, ar=27, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.11, as_ratio=0, mana=350, mana_growth=50)
Renekton = partial(Champion, name="Renekton", ad=69, ad_growth=4.15, hp=660, hp_growth=111, ar=35, ar_growth=5.2, mr=32,
            mr_growth=2.05, base_aspd=0.665, aspd_growth=2.75, as_ratio=0, mana=100, mana_growth=0)
Rengar = partial(Champion, name="Rengar", ad=68, ad_growth=3, hp=655, hp_growth=104, ar=34, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.667, aspd_growth=3, as_ratio=0, mana=4, mana_growth=0)
Riven = partial(Champion, name="Riven", ad=64, ad_growth=3, hp=630, hp_growth=100, ar=33, ar_growth=4.4, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=3.5, as_ratio=0, mana=0, mana_growth=0)
Rumble = partial(Champion, name="Rumble", ad=61, ad_growth=3.2, hp=659, hp_growth=99, ar=36, ar_growth=4.7, mr=28,
            mr_growth=1.55, base_aspd=0.644, aspd_growth=1.85, as_ratio=0, mana=100, mana_growth=0)
Ryze = partial(Champion, name="Ryze", ad=58, ad_growth=3, hp=645, hp_growth=124, ar=22, ar_growth=4.2, mr=36,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.112, as_ratio=0, mana=300, mana_growth=70)
Samira = partial(Champion, name="Samira", ad=57, ad_growth=3, hp=600, hp_growth=108, ar=26, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.658, aspd_growth=3.3, as_ratio=0, mana=348.88, mana_growth=38)
Sejuani = partial(Champion, name="Sejuani", ad=66, ad_growth=4, hp=630, hp_growth=114, ar=34, ar_growth=5.45, mr=32,
            mr_growth=2.05, base_aspd=0.688, aspd_growth=3.5, as_ratio=0.625, mana=400, mana_growth=40)
Senna = partial(Champion, name="Senna", ad=50, ad_growth=0, hp=590, hp_growth=89, ar=28, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=4, as_ratio=0.3, mana=350, mana_growth=45)
Seraphine = partial(Champion, name="Seraphine", ad=55, ad_growth=3, hp=570, hp_growth=104, ar=19, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.669, aspd_growth=1, as_ratio=0.625, mana=440, mana_growth=40)
Sett = partial(Champion, name="Sett", ad=60, ad_growth=4, hp=670, hp_growth=114, ar=33, ar_growth=5.2, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=1.75, as_ratio=0, mana=0, mana_growth=0)
Shaco = partial(Champion, name="Shaco", ad=63, ad_growth=3, hp=630, hp_growth=103, ar=30, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.694, aspd_growth=3, as_ratio=0, mana=297, mana_growth=40)
Shen = partial(Champion, name="Shen", ad=60, ad_growth=3, hp=610, hp_growth=99, ar=34, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.751, aspd_growth=3, as_ratio=0.651, mana=400, mana_growth=0)
Shyvana = partial(Champion, name="Shyvana", ad=66, ad_growth=3.4, hp=665, hp_growth=109, ar=38, ar_growth=4.55, mr=32,
            mr_growth=2.05, base_aspd=0.658, aspd_growth=2.5, as_ratio=0, mana=100, mana_growth=0)
Singed = partial(Champion, name="Singed", ad=63, ad_growth=3.38, hp=650, hp_growth=99, ar=34, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.613, aspd_growth=1.9, as_ratio=0, mana=330, mana_growth=45)
Sion = partial(Champion, name="Sion", ad=68, ad_growth=4, hp=615, hp_growth=87, ar=32, ar_growth=4.2, mr=32,
            mr_growth=2.05, base_aspd=0.679, aspd_growth=1.3, as_ratio=0, mana=330, mana_growth=42)
Sivir = partial(Champion, name="Sivir", ad=63, ad_growth=3, hp=632, hp_growth=104, ar=26, ar_growth=4.45, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.6, as_ratio=0, mana=325, mana_growth=50)
Skarner = partial(Champion, name="Skarner", ad=65, ad_growth=4.5, hp=650, hp_growth=99, ar=38, ar_growth=5, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=2.1, as_ratio=0, mana=320, mana_growth=60)
Sona = partial(Champion, name="Sona", ad=49, ad_growth=3, hp=550, hp_growth=91, ar=26, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.644, aspd_growth=2.3, as_ratio=0, mana=340, mana_growth=45)
Soraka = partial(Champion, name="Soraka", ad=50, ad_growth=3, hp=605, hp_growth=88, ar=32, ar_growth=5, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.14, as_ratio=0, mana=425, mana_growth=40)
Swain = partial(Champion, name="Swain", ad=58, ad_growth=2.7, hp=595, hp_growth=99, ar=26, ar_growth=5.2, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.11, as_ratio=0, mana=468, mana_growth=28.5)
Sylas = partial(Champion, name="Sylas", ad=61, ad_growth=3, hp=595, hp_growth=129, ar=27, ar_growth=5.2, mr=32,
            mr_growth=2.55, base_aspd=0.645, aspd_growth=3.5, as_ratio=0, mana=310, mana_growth=70)
Syndra = partial(Champion, name="Syndra", ad=54, ad_growth=2.9, hp=593, hp_growth=104, ar=25, ar_growth=4.6, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2, as_ratio=0, mana=480, mana_growth=40)
TahmKench = partial(Champion, name="TahmKench", ad=56, ad_growth=3.2, hp=640, hp_growth=109, ar=42, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.658, aspd_growth=2.5, as_ratio=0, mana=325, mana_growth=50)
Taliyah = partial(Champion, name="Taliyah", ad=58, ad_growth=3.3, hp=570, hp_growth=104, ar=18, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.36, as_ratio=0, mana=470, mana_growth=30)
Talon = partial(Champion, name="Talon", ad=68, ad_growth=3.1, hp=658, hp_growth=109, ar=30, ar_growth=4.7, mr=39,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=2.9, as_ratio=0, mana=377.2, mana_growth=37)
Taric = partial(Champion, name="Taric", ad=55, ad_growth=3.5, hp=645, hp_growth=99, ar=40, ar_growth=4.6, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=2, as_ratio=0, mana=300, mana_growth=60)
Teemo = partial(Champion, name="Teemo", ad=54, ad_growth=3, hp=598, hp_growth=104, ar=24, ar_growth=4.95, mr=30,
            mr_growth=1.3, base_aspd=0.69, aspd_growth=3.38, as_ratio=0, mana=334, mana_growth=20)
Thresh = partial(Champion, name="Thresh", ad=56, ad_growth=2.2, hp=600, hp_growth=115, ar=28, ar_growth=0, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=3.5, as_ratio=0, mana=274, mana_growth=44)
Tristana = partial(Champion, name="Tristana", ad=59, ad_growth=3.7, hp=670, hp_growth=102, ar=26, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.656, aspd_growth=1.5, as_ratio=0.679, mana=250, mana_growth=32)
Trundle = partial(Champion, name="Trundle", ad=68, ad_growth=3, hp=686, hp_growth=110, ar=37, ar_growth=3.9, mr=32,
            mr_growth=2.05, base_aspd=0.67, aspd_growth=2.9, as_ratio=0, mana=281, mana_growth=45)
Tryndamere = partial(Champion, name="Tryndamere", ad=72, ad_growth=3.7, hp=696, hp_growth=112, ar=33, ar_growth=4.3, mr=32,
            mr_growth=2.05, base_aspd=0.67, aspd_growth=2.9, as_ratio=0, mana=100, mana_growth=0)
TwistedFate = partial(Champion, name="TwistedFate", ad=52, ad_growth=3.3, hp=604, hp_growth=108, ar=21, ar_growth=4.35, mr=30,
            mr_growth=1.3, base_aspd=0.651, aspd_growth=3.22, as_ratio=0, mana=333, mana_growth=39)
Twitch = partial(Champion, name="Twitch", ad=59, ad_growth=3.11, hp=682, hp_growth=100, ar=27, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.679, aspd_growth=3.38, as_ratio=0, mana=287.2, mana_growth=40)
Udyr = partial(Champion, name="Udyr", ad=64, ad_growth=5, hp=664, hp_growth=106, ar=34, ar_growth=5.2, mr=32,
            mr_growth=2.05, base_aspd=0.658, aspd_growth=2.67, as_ratio=0, mana=271, mana_growth=50)
Urgot = partial(Champion, name="Urgot", ad=63, ad_growth=4, hp=655, hp_growth=102, ar=36, ar_growth=5.45, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=3.75, as_ratio=0, mana=340, mana_growth=45)
Varus = partial(Champion, name="Varus", ad=59, ad_growth=3.4, hp=600, hp_growth=105, ar=27, ar_growth=4.6, mr=30,
            mr_growth=1.3, base_aspd=0.658, aspd_growth=4, as_ratio=0, mana=360, mana_growth=40)
Vayne = partial(Champion, name="Vayne", ad=60, ad_growth=2.36, hp=585, hp_growth=103, ar=23, ar_growth=4.6, mr=30,
            mr_growth=1.3, base_aspd=0.658, aspd_growth=3.3, as_ratio=0, mana=231.8, mana_growth=35)
Veigar = partial(Champion, name="Veigar", ad=52, ad_growth=2.7, hp=575, hp_growth=108, ar=21, ar_growth=5.2, mr=32,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.24, as_ratio=0, mana=490, mana_growth=26)
Velkoz = partial(Champion, name="Velkoz", ad=55, ad_growth=3.1416, hp=590, hp_growth=102, ar=22, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.36, as_ratio=0, mana=469, mana_growth=21)
Vex = partial(Champion, name="Vex", ad=54, ad_growth=2.75, hp=590, hp_growth=104, ar=23, ar_growth=4.45, mr=28,
            mr_growth=1.3, base_aspd=0.669, aspd_growth=1, as_ratio=0.625, mana=490, mana_growth=32)
Vi = partial(Champion, name="Vi", ad=63, ad_growth=3, hp=655, hp_growth=99, ar=30, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.644, aspd_growth=2, as_ratio=0, mana=295, mana_growth=65)
Viego = partial(Champion, name="Viego", ad=57, ad_growth=3.5, hp=630, hp_growth=109, ar=34, ar_growth=5.2, mr=32,
            mr_growth=2.05, base_aspd=0.658, aspd_growth=2.5, as_ratio=0, mana=10000, mana_growth=0)
Viktor = partial(Champion, name="Viktor", ad=53, ad_growth=3, hp=600, hp_growth=104, ar=23, ar_growth=5.2, mr=30,
            mr_growth=1.3, base_aspd=0.658, aspd_growth=2.11, as_ratio=0, mana=405, mana_growth=45)
Vladimir = partial(Champion, name="Vladimir", ad=55, ad_growth=3, hp=607, hp_growth=110, ar=27, ar_growth=4.5, mr=30,
            mr_growth=1.3, base_aspd=0.658, aspd_growth=2, as_ratio=0, mana=2, mana_growth=0)
Volibear = partial(Champion, name="Volibear", ad=60, ad_growth=3.5, hp=650, hp_growth=104, ar=31, ar_growth=5.2, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=2, as_ratio=0.7, mana=350, mana_growth=70)
Warwick = partial(Champion, name="Warwick", ad=65, ad_growth=3, hp=620, hp_growth=99, ar=33, ar_growth=4.4, mr=32,
            mr_growth=2.05, base_aspd=0.638, aspd_growth=2.3, as_ratio=0, mana=280, mana_growth=35)
Xayah = partial(Champion, name="Xayah", ad=60, ad_growth=3.5, hp=660, hp_growth=102, ar=25, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=3.9, as_ratio=0, mana=340, mana_growth=40)
Xerath = partial(Champion, name="Xerath", ad=55, ad_growth=3, hp=596, hp_growth=106, ar=22, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=1.36, as_ratio=0, mana=459, mana_growth=22)
XinZhao = partial(Champion, name="XinZhao", ad=63, ad_growth=3, hp=640, hp_growth=106, ar=35, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.645, aspd_growth=3.5, as_ratio=0, mana=274, mana_growth=55)
Yasuo = partial(Champion, name="Yasuo", ad=60, ad_growth=3, hp=590, hp_growth=101, ar=30, ar_growth=4.6, mr=32,
            mr_growth=2.05, base_aspd=0.697, aspd_growth=3.5, as_ratio=0.67, mana=100, mana_growth=0)
Yone = partial(Champion, name="Yone", ad=60, ad_growth=2, hp=620, hp_growth=99, ar=28, ar_growth=4.6, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=3.5, as_ratio=0, mana=500, mana_growth=0)
Yorick = partial(Champion, name="Yorick", ad=62, ad_growth=5, hp=650, hp_growth=114, ar=39, ar_growth=5.2, mr=32,
            mr_growth=2.05, base_aspd=0.625, aspd_growth=2, as_ratio=0, mana=300, mana_growth=60)
Yuumi = partial(Champion, name="Yuumi", ad=55, ad_growth=3.1, hp=550, hp_growth=84, ar=25, ar_growth=4.2, mr=25,
            mr_growth=1.1, base_aspd=0.625, aspd_growth=1, as_ratio=0, mana=400, mana_growth=45)
Zac = partial(Champion, name="Zac", ad=60, ad_growth=3.4, hp=685, hp_growth=109, ar=33, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.736, aspd_growth=1.6, as_ratio=0.638, mana=0, mana_growth=0)
Zed = partial(Champion, name="Zed", ad=63, ad_growth=3.4, hp=654, hp_growth=99, ar=32, ar_growth=4.7, mr=32,
            mr_growth=2.05, base_aspd=0.651, aspd_growth=3.3, as_ratio=0, mana=200, mana_growth=0)
Zeri = partial(Champion, name="Zeri", ad=50, ad_growth=1.5, hp=600, hp_growth=109, ar=20, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.658, aspd_growth=2, as_ratio=0.568, mana=250, mana_growth=45)
Ziggs = partial(Champion, name="Ziggs", ad=54, ad_growth=3.1, hp=606, hp_growth=106, ar=22, ar_growth=4.5, mr=30,
            mr_growth=1.3, base_aspd=0.656, aspd_growth=2, as_ratio=0, mana=480, mana_growth=23.5)
Zilean = partial(Champion, name="Zilean", ad=52, ad_growth=3, hp=574, hp_growth=96, ar=24, ar_growth=5, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.13, as_ratio=0, mana=452, mana_growth=50)
Zoe = partial(Champion, name="Zoe", ad=58, ad_growth=3.3, hp=630, hp_growth=106, ar=21, ar_growth=4.7, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.5, as_ratio=0, mana=425, mana_growth=25)
Zyra = partial(Champion, name="Zyra", ad=53, ad_growth=3.2, hp=574, hp_growth=93, ar=29, ar_growth=4.2, mr=30,
            mr_growth=1.3, base_aspd=0.625, aspd_growth=2.11, as_ratio=0, mana=418, mana_growth=25)



